// Partially generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;

import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.Instant;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class DataScraper {
  class ClientRowData {
    String clientFirstName = "";
    String clientLastName = "";
    String clientAddress = "";
    String caseNumber = "";
    String courtDate = "";
    String room = "";
    String location = "";
    String landlord = "";
    String trimString(String s) {
      return s.trim().replace(",", "").replace("\n", " ");
    }
    String rowData() {
      return this.trimString(caseNumber) + ',' +
            this.trimString(clientLastName) + ',' +
            this.trimString(clientFirstName) + ',' +
            this.trimString(clientAddress) + ',' +
            this.trimString(courtDate) + ',' +
            this.trimString(location) + ',' +
            this.trimString(room) + ',' +
            this.trimString(landlord);
    }
    void print() {
      System.out.println(this.rowData());
    }
}
  private void doSleep(int seconds) {
    try {
      Thread.sleep(seconds * 1000);
    } catch (InterruptedException e) {
      // TO DO Auto-generated catch block
      e.printStackTrace();
    }
  }
  void getCourtData(ClientRowData crd) {
    crd.courtDate = driver.findElement(By.cssSelector("a:nth-child(5) td:nth-child(2)")).getText();
    crd.room = driver.findElement(By.cssSelector("a:nth-child(5) td:nth-child(3)")).getText();
    crd.location = driver.findElement(By.cssSelector("a:nth-child(5) td:nth-child(4)")).getText();
  }
  void dumpThrowable(Throwable t, ClientRowData crd) {
    skipCount++;
    if (this.showExceptions) {
      String[] lines = t.getMessage().split("\n");
      System.out.println("0," + crd.rowData() + "," + lines[0]);
    }
  }
  void fillInCourtInfo(ClientRowData crd) {
    if (!crd.caseNumber.isEmpty()) {
      driver.findElement(By.linkText(crd.caseNumber)).click();
      try {
        driver.switchTo().frame(1);
        this.getCourtData(crd);
        crd.print();
        this.caseCount++;
      } catch(Throwable e) {
        this.dumpThrowable(e, crd);
        // Assume no (or incomplete) case event history. Continue to the next row in the case list.
      }              
      this.js.executeScript("window.history.go(-1)");
    }
  }
  void fillInCaseAndLandlord(ClientRowData crd, Integer rowNumber) {
    final String ADDRESS_COLUMN = "3";
    final String cellText = driver.findElement(By.cssSelector(
            "tr:nth-child(" + rowNumber.toString() + ") > td:nth-child(" + ADDRESS_COLUMN + ")")).getText();    
    String[] chunks = cellText.split("Case:");
    crd.clientAddress = chunks[0];
    crd.landlord = chunks[1].split("V")[0].substring(9);
    Pattern pattern = Pattern.compile("\\d\\d\\d\\d\\d\\d\\d", Pattern.CASE_INSENSITIVE);
    Matcher matcher = pattern.matcher(cellText);
    if (matcher.find()) {
      crd.caseNumber = matcher.group();
    } else {
      System.out.println("No 7-digit case# in: " + cellText);
    }
  }
  void setDefendantName(ClientRowData crd, String defendant_name) {
    if (defendant_name.contains(",")) {
      String[] names = defendant_name.split(","); // last, first
      crd.clientLastName = names[0];
      crd.clientFirstName = names[1];
    } else {
      crd.clientLastName = defendant_name;
    }
  }
void fillInDefendantInfo(Integer rowNumber) {
    ClientRowData crd = new ClientRowData();      
    final String NAME_CORPORATION_COLUMN = "2";
    final String defendant_name = driver.findElement(By.cssSelector(
            "tr:nth-child(" + rowNumber.toString() + ") > td:nth-child(" + NAME_CORPORATION_COLUMN + ")")).getText();
    this.setDefendantName(crd, defendant_name);
    this.fillInCaseAndLandlord(crd, rowNumber);
    this.fillInCourtInfo(crd);
  }
  private void getDefendant(ClientRowData crd) {
    final String defendantName = driver.findElement(By.cssSelector(
        "tr:nth-child(5) b")).getText();
    this.setDefendantName(crd, defendantName);
    final String defendantAddress = driver.findElement(By.cssSelector(
        "a:nth-child(6) tr:nth-child(6) > td:nth-child(2)")).getText();
    crd.clientAddress = defendantAddress; 
  }
  public void showSpecificCases() {
    if (driver == null) {
      driver = new ChromeDriver();
    }
    final String url = "https://gscivildata.shelbycountytn.gov/pls/gnweb/ck_public_qry_doct.cp_dktrpt_frames?case_id=";
    final String[] caseNumbers = new String[]{"2101305"};
    for (String s : caseNumbers) {
      driver.get(url + s);
      this.doSleep(30);
    }
  }
  private void getDefendantInfoFromCase(Integer rowNumber) {
    ClientRowData crd = new ClientRowData();
    this.fillInCaseAndLandlord(crd, rowNumber);
    driver.findElement(By.linkText(crd.caseNumber)).click();
    try {
      driver.switchTo().frame(1);
      this.getCourtData(crd);
      this.getDefendant(crd);
      crd.print();
      this.caseCount++;
    } catch(Throwable e) {
      this.dumpThrowable(e, crd);
    }              
    this.js.executeScript("window.history.go(-1)");
  }
  void scrapeOnePage() {
    boolean switchFrame = true;
    while (true) {
      for (Integer rowNumber = 2; rowNumber < 22; rowNumber++) {
        try {
          if (switchFrame) {
            driver.switchTo().frame(1);
          } else {
            switchFrame = true;
          }
          // Firefox fails here with "NoSuchWindowError: Browsing context has been discarded"
          final String PARTY_TYPE_COLUMN = "4";
          final String party_type = driver.findElement(By.cssSelector("tr:nth-child(" + rowNumber.toString() + ") > td:nth-child(" + PARTY_TYPE_COLUMN + ")")).getText();
          if (party_type.equals("DEFENDANT")) {
            fillInDefendantInfo(rowNumber);
          } else if (party_type.equals("PLAINTIFF")) {
            getDefendantInfoFromCase(rowNumber);
          } else {
            skipCount++;
            switchFrame = false;
          }
        } catch(Throwable t) {
          // Assume we ran out of rows on this page.
          break;
        }
      }
      try {
        if (switchFrame) {
          driver.switchTo().frame(1);
        }
        driver.findElement(By.linkText("Next->")).click();
      } catch(Throwable t) {
          // Assume we ran out of clients beginning with 'firstLetter'.
          return;
      }
      switchFrame = false;
    }
  }
  private SimpleDateFormat df = new SimpleDateFormat("dd-MMM-YYYY");
  String getFirstDate() {
    if (this.args.length > 0) {
      return this.args[0];
    }
    Calendar c = Calendar.getInstance();
    c.set(Calendar.DAY_OF_MONTH, 1);
    return df.format(c.getTime());
  }
  String getLastDate() {
    if (this.args.length > 1) {
      return this.args[1];
    }
    return df.format(Calendar.getInstance().getTime());
  }
  void scrapeByFirstLetter(String firstLetter) {
    driver.get("https://gscivildata.shelbycountytn.gov/pls/gnweb/ck_public_qry_cpty.cp_personcase_setup_idx");
    driver.switchTo().frame(1);
    driver.findElement(By.name("partial_ind")).click();
    driver.findElement(By.name("last_name")).click();
    driver.findElement(By.name("last_name")).sendKeys(firstLetter);
    driver.findElement(By.name("begin_date")).click();
    driver.findElement(By.name("begin_date")).sendKeys(this.getFirstDate());
    driver.findElement(By.cssSelector("tr:nth-child(7) > td:nth-child(1)")).click();
    driver.findElement(By.name("end_date")).click();
    driver.findElement(By.name("end_date")).sendKeys(this.getLastDate());
    driver.findElement(By.name("case_type")).click();

    driver.findElement(By.cssSelector("option:nth-child(17)")).click();
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    this.scrapeOnePage();
  }
  private String padDigit(Long n) {
    if (n < 10) {
      return "0" + n.toString();
    }
    return n.toString();
  }
  private String[] args;
  private boolean showExceptions = false;
  private Long caseCount = 0L;
  private Long skipCount = 0L;
  private WebDriver driver;
  JavascriptExecutor js;
  
  public void scrapeData(String[] args) {
    this.args = args;
//    this.args = new String[] {"01-NOV-2021", "30-NOV-2021", "A"};
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    Instant start = Instant.now();
    char lastChar = 'Z';
    if (this.args.length > 2) {
      lastChar = this.args[2].charAt(0);
    }
    if (this.args.length > 3) {
      showExceptions = true;
    }
    for (char c = 'A'; c <= lastChar; c++) {
      this.scrapeByFirstLetter(Character.toString(c));
    }
    driver.quit();
    System.err.println("0,caseCount," + caseCount);
    System.err.println("0,skipCount," + skipCount);
    Long timeElapsed = Duration.between(start, Instant.now()).toMillis() / 1000;
    Long minutes = timeElapsed / 60;
    Long seconds = timeElapsed % 60;
    String elapsed = this.padDigit(minutes) + ":" + this.padDigit(seconds);
    System.err.println("0,duration(MM:SS)," + elapsed);
  }
  public static void main(String[] args) {
      new DataScraper().showSpecificCases(); // scrapeData(args);
  }
}
